// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlite

import ()

type Asset struct {
	ID   int64  `json:"id"`
	Path string `json:"path"`
	Name string `json:"name"`
}
